### ISSUE TITLE
Unable to use in Atom: unrecognized arguments: -f

### ISSUE THREAD

**Issue by Treverr** [lovesegfault/beautysh#63]
```
usage: beautysh [--indent-size INDENT_SIZE] [--backup] [--check] [--tab]
                [--force-function-style FORCE_FUNCTION_STYLE] [--version]
                [--help]
                [FILE [FILE ...]]
beautysh: error: unrecognized arguments: -f
Hide Stack Trace
Error: usage: beautysh [--indent-size INDENT_SIZE] [--backup] [--check] [--tab]
                [--force-function-style FORCE_FUNCTION_STYLE] [--version]
                [--help]
                [FILE [FILE ...]]
beautysh: error: unrecognized arguments: -f
    at /Users/treverchambersewing/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/Users/treverchambersewing/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/treverchambersewing/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/treverchambersewing/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/treverchambersewing/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/treverchambersewing/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/treverchambersewing/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/treverchambersewing/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/treverchambersewing/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:147:5)
    at Async.drainQueues (/Users/treverchambersewing/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by lovesegfault** [comment]
This is a bug in `atom-beautify` and not in beautysh. They need to update the way they call `beautysh` since we got rid of the `-f` flag a long time ago.

**Comment by TheRussianHetzer** [comment]
Let post the [unofficial solution ](https://github.com/Glavin001/atom-beautify/issues/2510#issuecomment-677825594)they give us here, easily access.
